export const VIDEO_FORMATS = {
  preview: {
    priority: 2,
    container: 'mp4',
    mimeType: 'video/mp4',
    codecString: 'avc1.42E01E',
    maxWidth: 854,
    maxHeight: 480,
    ffmpegArgs: [
      '-c:v',
      'libx264',
      '-crf',
      '28',
      '-preset',
      'faster',
      '-profile:v',
      'baseline',
      '-level',
      '3.1',
      '-g',
      '60',
      '-maxrate',
      '1M',
      '-bufsize',
      '2M',
      '-an',
      '-movflags',
      '+faststart',
      '-pix_fmt',
      'yuv420p',
    ],
  },
  webm: {
    priority: 0,
    container: 'webm',
    mimeType: 'video/webm',
    codecString: 'vp9',
    maxWidth: 1920,
    maxHeight: 1080,
    ffmpegArgs: [
      '-c:v',
      'libvpx-vp9',
      '-crf',
      '24',
      '-b:v',
      '4M',
      '-g',
      '60',
      '-maxrate',
      '6M',
      '-bufsize',
      '12M',
      '-c:a',
      'libopus',
      '-b:a',
      '128k',
      '-row-mt',
      '1',
      '-max_muxing_queue_size',
      '1024',
    ],
  },
  mp4: {
    priority: 1,
    container: 'mp4',
    mimeType: 'video/mp4',
    codecString: 'avc1.4d401f',
    maxWidth: 1920,
    maxHeight: 1080,
    ffmpegArgs: [
      '-c:v',
      'libx264',
      '-crf',
      '21',
      '-preset',
      'medium',
      '-profile:v',
      'main',
      '-level',
      '4.0',
      '-g',
      '60',
      '-maxrate',
      '5M',
      '-bufsize',
      '10M',
      '-c:a',
      'aac',
      '-b:a',
      '128k',
      '-movflags',
      '+faststart',
      '-pix_fmt',
      'yuv420p',
      '-max_muxing_queue_size',
      '1024',
    ],
  },
} as const;

export const COMMON_VIDEO_ARGS = ['-r', '30', '-map', '0:v:0', '-map', '0:a?'];
export const PREVIEW_VIDEO_ARGS = ['-r', '30', '-map', '0:v:0'];

export type VideoFormat = keyof typeof VIDEO_FORMATS;
export const FULL_FORMAT_PRIORITY: VideoFormat[] = ['webm', 'mp4'];
export const ALL_FORMATS: VideoFormat[] = ['preview', 'webm', 'mp4'];
