import type {
  CreditsAnchorX,
  CreditsAnchorY,
  CreditsBackgroundMode,
  CreditsScrollDirection,
  CreditsTextAlign,
  CreditsTitleTransform,
} from '../types';

type SetState<T> = (value: T) => void;

export type CreditsSettingsLoaderState = {
  setCreditsToken: SetState<string>;
  setCreditsUrl: SetState<string>;
  setLoadingCreditsToken: SetState<boolean>;
  setLoadingCreditsSettings: SetState<boolean>;
  setLastSavedCreditsSettingsPayload: SetState<string | null>;
  creditsSettingsLoadedRef: React.MutableRefObject<string | null>;
  creditsSectionsOrder: Array<'donors' | 'chatters'>;
  setCreditsSectionsOrder: SetState<Array<'donors' | 'chatters'>>;
  creditsShowDonors: boolean;
  setCreditsShowDonors: SetState<boolean>;
  creditsShowChatters: boolean;
  setCreditsShowChatters: SetState<boolean>;
  creditsTitleText: string;
  setCreditsTitleText: SetState<string>;
  creditsDonorsTitleText: string;
  setCreditsDonorsTitleText: SetState<string>;
  creditsChattersTitleText: string;
  setCreditsChattersTitleText: SetState<string>;
  creditsShowNumbers: boolean;
  setCreditsShowNumbers: SetState<boolean>;
  creditsShowAvatars: boolean;
  setCreditsShowAvatars: SetState<boolean>;
  creditsAvatarSize: number;
  setCreditsAvatarSize: SetState<number>;
  creditsAvatarRadius: number;
  setCreditsAvatarRadius: SetState<number>;
  creditsFontFamily: string;
  setCreditsFontFamily: SetState<string>;
  creditsFontSize: number;
  setCreditsFontSize: SetState<number>;
  creditsFontWeight: number;
  setCreditsFontWeight: SetState<number>;
  creditsFontColor: string;
  setCreditsFontColor: SetState<string>;
  creditsBgOpacity: number;
  setCreditsBgOpacity: SetState<number>;
  creditsBlur: number;
  setCreditsBlur: SetState<number>;
  creditsRadius: number;
  setCreditsRadius: SetState<number>;
  creditsShadowBlur: number;
  setCreditsShadowBlur: SetState<number>;
  creditsShadowOpacity: number;
  setCreditsShadowOpacity: SetState<number>;
  creditsBgColor: string;
  setCreditsBgColor: SetState<string>;
  creditsBackgroundMode: CreditsBackgroundMode;
  setCreditsBackgroundMode: SetState<CreditsBackgroundMode>;
  creditsBorderEnabled: boolean;
  setCreditsBorderEnabled: SetState<boolean>;
  creditsBorderWidth: number;
  setCreditsBorderWidth: SetState<number>;
  creditsBorderColor: string;
  setCreditsBorderColor: SetState<string>;
  creditsAnchorX: CreditsAnchorX;
  setCreditsAnchorX: SetState<CreditsAnchorX>;
  creditsAnchorY: CreditsAnchorY;
  setCreditsAnchorY: SetState<CreditsAnchorY>;
  creditsBgInsetLeft: number;
  setCreditsBgInsetLeft: SetState<number>;
  creditsBgInsetRight: number;
  setCreditsBgInsetRight: SetState<number>;
  creditsBgInsetTop: number;
  setCreditsBgInsetTop: SetState<number>;
  creditsBgInsetBottom: number;
  setCreditsBgInsetBottom: SetState<number>;
  creditsContentPadLeft: number;
  setCreditsContentPadLeft: SetState<number>;
  creditsContentPadRight: number;
  setCreditsContentPadRight: SetState<number>;
  creditsContentPadTop: number;
  setCreditsContentPadTop: SetState<number>;
  creditsContentPadBottom: number;
  setCreditsContentPadBottom: SetState<number>;
  creditsMaxWidthPx: number;
  setCreditsMaxWidthPx: SetState<number>;
  creditsMaxHeightVh: number;
  setCreditsMaxHeightVh: SetState<number>;
  creditsTextAlign: CreditsTextAlign;
  setCreditsTextAlign: SetState<CreditsTextAlign>;
  creditsIndentPx: number;
  setCreditsIndentPx: SetState<number>;
  creditsLineHeight: number;
  setCreditsLineHeight: SetState<number>;
  creditsLetterSpacing: number;
  setCreditsLetterSpacing: SetState<number>;
  creditsTitleEnabled: boolean;
  setCreditsTitleEnabled: SetState<boolean>;
  creditsTitleSize: number;
  setCreditsTitleSize: SetState<number>;
  creditsTitleWeight: number;
  setCreditsTitleWeight: SetState<number>;
  creditsTitleColor: string;
  setCreditsTitleColor: SetState<string>;
  creditsTitleTransform: CreditsTitleTransform;
  setCreditsTitleTransform: SetState<CreditsTitleTransform>;
  creditsTextShadowBlur: number;
  setCreditsTextShadowBlur: SetState<number>;
  creditsTextShadowOpacity: number;
  setCreditsTextShadowOpacity: SetState<number>;
  creditsTextShadowColor: string;
  setCreditsTextShadowColor: SetState<string>;
  creditsTextStrokeWidth: number;
  setCreditsTextStrokeWidth: SetState<number>;
  creditsTextStrokeOpacity: number;
  setCreditsTextStrokeOpacity: SetState<number>;
  creditsTextStrokeColor: string;
  setCreditsTextStrokeColor: SetState<string>;
  creditsTitleShadowBlur: number;
  setCreditsTitleShadowBlur: SetState<number>;
  creditsTitleShadowOpacity: number;
  setCreditsTitleShadowOpacity: SetState<number>;
  creditsTitleShadowColor: string;
  setCreditsTitleShadowColor: SetState<string>;
  creditsTitleStrokeWidth: number;
  setCreditsTitleStrokeWidth: SetState<number>;
  creditsTitleStrokeOpacity: number;
  setCreditsTitleStrokeOpacity: SetState<number>;
  creditsTitleStrokeColor: string;
  setCreditsTitleStrokeColor: SetState<string>;
  creditsScrollSpeed: number;
  setCreditsScrollSpeed: SetState<number>;
  creditsScrollDirection: CreditsScrollDirection;
  setCreditsScrollDirection: SetState<CreditsScrollDirection>;
  creditsLoop: boolean;
  setCreditsLoop: SetState<boolean>;
  creditsStartDelayMs: number;
  setCreditsStartDelayMs: SetState<number>;
  creditsEndFadeMs: number;
  setCreditsEndFadeMs: SetState<number>;
  creditsSectionGapPx: number;
  setCreditsSectionGapPx: SetState<number>;
  creditsLineGapPx: number;
  setCreditsLineGapPx: SetState<number>;
  creditsFadeInMs: number;
  setCreditsFadeInMs: SetState<number>;
};
