export type SettingsTab =
  | 'settings'
  | 'rewards'
  | 'obs'
  | 'bot'
  | 'accounts'
  | 'wallets'
  | 'promotions'
  | 'statistics'
  | 'beta'
  | 'entitlements'
  | 'ownerMemeAssets'
  | 'ownerModerators'
  | 'ownerAiStatus'
  | 'ownerTagModeration';
